camunda:
  bpm:
    database.schema-update: true
    job-execution:
      deployment-aware: true
      max-wait: 10000
    admin-user:
      id: demo
      password: demo
      firstName: Demo
    filter:
      create: All tasks
    generic-properties:
      properties:
        enableExceptionsAfterUnhandledBpmnError: true

spring:
   datasource:
     url: jdbc:h2:file:./camunda;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
     username: sa
     password: sa